---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: server-app-cartrawler
  name: server-app-cartrawler
spec:
  ports:
  - name: 8000-8000
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: server-app-cartrawler
  type: NodePort
status:
  loadBalancer: {}
