pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-1'
    ECR_REPO = 'your-ecr-repo-url'
    IMAGE_TAG = "server-app:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Checkout') {
      steps {
		git https://github.com/frfavoreto/senior-devops-tech-test.git
      }
  }

  stage('Lint') {
    steps {
      sh 'yamllint k8s/'
    }
  }

  stage('Test') {
    steps {
      dir('app') {
      sh 'npm install'
      sh 'npm test'
      }
    }
  }

  stage('Build Docker Image') {
    steps {
      script {
        dockerimage = docker.build("$IMAGE_TAG", './app')
      }
    }i
  }

  stage('Push to ECR') {
    steps {
      echo 'Simulate push to ECR or implement AWS CLI commands here'
    }
  }

  stage('Deploy to EKS') {
    steps {
      echo 'Simulate deploy to EKS or run kubectl apply'
    }
  }
  }
  
  post {
    always {
      echo 'Pipeline completed.'
    }
  }
}
