---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
    - name: {{ .Values.containerPort }}-{{ .Values.containerPort }}
      port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.serviceType }}
status:
  loadBalancer: {}
